{{ if .Values.thanos.enabled }} 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.thanos.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.thanos.syncWave | default "0" | quote }}
spec:
  project: {{ .Values.global.project }}
  destination: 
    namespace: {{ .Values.thanos.namespace }}
    server: {{ .Values.global.clusterURL }}
  source:
    repoURL: {{ .Values.thanos.source.repoURL }}
    chart: {{ .Values.thanos.source.chart }} 
    targetRevision: {{ .Values.thanos.source.targetRevision | default "HEAD" }}
    helm:
      releaseName: {{ .Values.thanos.name }}
{{- with .Values.thanos.values }}
      values: |-
{{- toYaml . | nindent 8 }}
{{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: route.openshift.io/v1                                                                                    
kind: Route                                                                                                          
metadata:
  name: {{ .Values.thanos.name }}                                                                                               
  namespace: {{ .Values.thanos.namespace }}                                                                                                                                                                       
spec:                                                                                                                
  host: {{ .Values.thanos.name }}.{{ .Values.global.baseDomain }}                                  
  port:                                                                                                              
    targetPort: remote                                                                                       
  to:                                                                                                                
    kind: Service                                                                                                    
    name: {{ .Values.thanos.name }}-receive                                                                                             
    weight: 100                                                                                                      
  wildcardPolicy: None                                                                                               
---
apiVersion: route.openshift.io/v1                                                                                    
kind: Route
metadata:
  name: {{ .Values.thanos.name }}-query                                                                                               
  namespace: {{ .Values.thanos.namespace }}                                                                                                                                                                       
spec:                                                                                                                
  host: {{ .Values.thanos.name }}-query.{{ .Values.global.baseDomain }}                                  
  port:                                                                                                              
    targetPort: http
  tls:
    termination: edge
  to:                                                                                                                
    kind: Service                                                                                                    
    name: {{ .Values.thanos.name }}-query                                                                                             
    weight: 100                                                                                                      
  wildcardPolicy: None      
---
apiVersion: route.openshift.io/v1                                                                                    
kind: Route                                                                                                          
metadata:
  name: {{ .Values.thanos.name }}-query-frontend                                                                                               
  namespace: {{ .Values.thanos.namespace }}                                                                                                                                                                       
spec:                                                                                                                
  host: {{ .Values.thanos.name }}-query-frontend.{{ .Values.global.baseDomain }}                                  
  port:                                                                                                              
    targetPort: http                                                                                         
  tls:
    termination: edge
  to:                                                                                                                
    kind: Service                                                                                                    
    name: {{ .Values.thanos.name }}-query-frontend                                                                                             
    weight: 100                                                                                                      
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1                                                                                    
kind: Route                                                                                                          
metadata:
  name: {{ .Values.thanos.name }}-bucketweb                                                                                             
  namespace: {{ .Values.thanos.namespace }}                                                                                                                                                                       
spec:                                                                                                                
  host: {{ .Values.thanos.name }}-bucketweb.{{ .Values.global.baseDomain }}                                  
  port:                                                                                                              
    targetPort: http                                                                                         
  to:                                                                                                                
    kind: Service                                                                                                    
    name: {{ .Values.thanos.name }}-bucketweb                                                                                             
    weight: 100                                                                                                      
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1                                                                                    
kind: Route                                                                                                          
metadata:
  name: {{ .Values.thanos.name }}-ruler                                                                                             
  namespace: {{ .Values.thanos.namespace }}                                                                                                                                                                       
spec:                                                                                                                
  host: {{ .Values.thanos.name }}-ruler.{{ .Values.global.baseDomain }}                                  
  port:                                                                                                              
    targetPort: http                                                                                         
  to:                                                                                                                
    kind: Service                                                                                                    
    name: {{ .Values.thanos.name }}-ruler                                                                                             
    weight: 100                                                                                                      
  wildcardPolicy: None  

                                                                                           
{{ end }}
