nameOverride: ""
fullnameOverride: "perf-results"
version: 7.15.2


ingress:
  enabled: true
  # DNS names will resolve as $hostName-(kibana | elastic).$hostedZone
  hostName: perf-results
  baseDomain: apps.keith-cluster.perfscale.devcluster.openshift.com

kibana:
  replicas: 1

elasticsearch:
  nodeSets:
  - name: default      
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Gi
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 16Gi
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
